version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - mongo
      - redis
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
